/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dictionary;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Collection;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import static dictionary.Giaodien.rf;
import javax.swing.JOptionPane;

/**
 * dinh 17020684
 * don 17020685
 * @author Pc
 */

public class Add extends javax.swing.JFrame {

    DictionaryManagement dm ;
    Write_ToFile Di;
    public Add(TreeMap<String,Word> tm) {
        initComponents();
        setTitle("Thêm Từ");
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        NewWordTarget.setText("");
        NewWordExplain.setText("");
      
        dm= new DictionaryManagement();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNewWord = new javax.swing.JLabel();
        lbNewRead = new javax.swing.JLabel();
        NewWordTarget = new javax.swing.JTextField();
        NewWordExplain = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNewWord.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNewWord.setForeground(new java.awt.Color(51, 102, 255));
        lbNewWord.setText("Từ mới");

        lbNewRead.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNewRead.setForeground(new java.awt.Color(51, 102, 255));
        lbNewRead.setText("Nghĩa");

        NewWordTarget.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewWordTarget.setForeground(new java.awt.Color(153, 0, 153));

        NewWordExplain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NewWordExplain.setForeground(new java.awt.Color(153, 0, 153));

        btAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btAdd.setForeground(new java.awt.Color(102, 102, 255));
        btAdd.setText("Thêm Từ");
        btAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddMouseClicked(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 51, 51));
        btCancel.setText("Hủy");
        btCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNewWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNewRead, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewWordTarget)
                    .addComponent(NewWordExplain))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewWordTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNewWord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewRead)
                    .addComponent(NewWordExplain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        int check;
        String word = NewWordTarget.getText();
        String read = NewWordExplain.getText();
        Word mWord = new Word(word,read);
        System.out.println(mWord);
        check = dm.checkword(mWord, Giaodien.rf.tm);
        System.out.println(Giaodien.rf.tm.keySet());
        if(check==dm.exsit)
              JOptionPane.showMessageDialog(null, "từ đã tồn tại");
        else if(check == dm.notFull)
                JOptionPane.showMessageDialog(null, "bạn chưa điền hết vào chỗ chống");
        else
        {
              JOptionPane.showMessageDialog(null, "Thêm từ thành công");
            try {
                Di = new Write_ToFile("Dictionaries");
                Di.Write(Giaodien.rf.tm.values());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            }
              
        }
    }//GEN-LAST:event_btAddMouseClicked

    private void btCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btCancelMouseClicked
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField NewWordExplain;
    public javax.swing.JTextField NewWordTarget;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel lbNewRead;
    private javax.swing.JLabel lbNewWord;
    // End of variables declaration//GEN-END:variables
}
